version: '3.8'

services:
  bank_app_db:
    container_name: bank_postgres_container
    image: postgres:16
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - bank-network

  app:
    container_name: bank-app-backend
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - bank_app_db
    env_file: .env
    environment:
      DB_HOST: bank_app_db
    networks:
      - bank-network


  # --- Stack de Monitoreo ---

  # Prometheus: Recolecta métricas numéricas (CPU, RAM, Requests)
  prometheus:
    image: prom/prometheus:latest
    container_name: bank_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - bank-network

  # Loki: Recolecta los logs de texto (Lo que sale en consola)
  loki:
    image: grafana/loki:2.9.2
    container_name: bank_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - bank-network

  # Grafana: Panel visual para ver todo
  grafana:
    image: grafana/grafana:latest
    container_name: bank_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin     # Usuario por defecto
      - GF_SECURITY_ADMIN_PASSWORD=admin # Contraseña por defecto
    depends_on:
      - prometheus
      - loki
    networks:
      - bank-network
volumes:
  pgdata:

networks:
  bank-network:
    driver: bridge