global:
  scrape_interval: 5s # Leer m√©tricas cada 5 segundos

scrape_configs:
  - job_name: 'bank-app-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['bank-app-backend:8080']