name: Java CI/CD with Maven & Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # GitHub - m치quina Linux

    steps:
      # Descarga c칩digo del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Instala Java 17 en esa m치quina Linux
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Ejecuta los Tests
      - name: Build and Test with Maven
        run: ./mvnw verify
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          EXCHANGE_API_KEY: ${{ secrets.EXCHANGE_API_KEY }}
          EXCHANGE_API_URL: ${{ secrets.EXCHANGE_API_URL }}
          DB_USER: test_user
          DB_PASSWORD: test_password
          DB_NAME: test_db

  docker-push:
    needs: build-and-test # Solo corre si los tests pasan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Solo subir im치genes si es merge a Main

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Generar el .jar (saltando tests porque ya pasaron arriba)
      - name: Build JAR
        run: ./mvnw package -DskipTests

      # Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir y Subir Imagen
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bank-app-backend:latest